### ISSUE TITLE
when if video length is too long.

### ISSUE THREAD

**Issue by EternalNation** [PetterKraabol/Twitch-Chat-Downloader#1]
hi,
Your program works very well. Thank you.

However, when if video length is too long i failed to download chat log with this error message.

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='rechat.twitch.tv', port=443): Max retries exceeded with url:

Is there anyway to download chat log when if video length is too long?
Or is there anyway to download part of video?
(ex. 2:00:00 ~ 3:00:00)

**Comment by PetterKraabol** [comment]
The error message means Twitch is blocking you, as you're sending too many requests too fast. Did they block you for a long time?

I'll try to make it so you can specify a time interval. I might also add a cooldown timer for every *X* API requests to avoid being blocked.

**Comment by EternalNation** [comment]
It looks fine when video length is not over 1 hours.

Thanks for your reply.

I will close the issue.

**Comment by Gorrrg** [comment]
I was able to download chats just over 2hrs long with no problem with the current version. Did you add a cooldown? If so, it works here.
