### ISSUE TITLE
Would it be possible to download chat logs?

### ISSUE THREAD

**Issue by Kaszanas** [PetterKraabol/Twitch-Chat-Downloader#108]
Hello,

This is technically a feature request.
What are Your thoughts on introducing chat download along with respective video?
There are existing implementations of such code available.

Another question would be if it is possible to use TwitchLeecher as a command line tool - which would ease the pain of using 2 command line software one for downloading video another for downloading chat.

**Comment by garoto** [comment]
wrong repo?

**Comment by Kaszanas** [comment]
Yup @garoto closing :D
Damn. Embarassing.
