### ISSUE TITLE
Unable to parse video data

### ISSUE THREAD

**Issue by johnsonpeng5** [PetterKraabol/Twitch-Chat-Downloader#120]
Hi there; sorry to be a bother.

I was trying to load the function in a jupyter notebook (code below); but got an error message back saying "ParsingError: Unable to parse video data. Please try again.". I've made sure that the video is a live broadcast link; and have also tried the chatdownloader on different live broadcast videos. For some reason, the code works on a google colaboratory; but not on my own PC. 

Am I doing something wrong?

![image](https://user-images.githubusercontent.com/31191581/108659987-f6c0ff00-746e-11eb-8701-6f4a4d33271a.png)
![image](https://user-images.githubusercontent.com/31191581/108660120-fe80a380-746e-11eb-8e07-1487b3f76a43.png)

**Comment by xenova** [comment]
Are you perhaps referring to my repo: https://github.com/xenova/chat-downloader?

If so, you can open the issue there.
