### ISSUE TITLE
[request] Extract video URLs from the "videos/all" page

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#13]
A new command line option would be cool where you just enter the Twitch user name and the script extracts all the video IDs from that user's "videos/all" page and downloads the corresponding chats. It would make updating your chat logs to the newest and fixed format of Twitch-Chat-Downloader so much easier.

The Twitch API probably offers a convenient way to get the currently available VODs, so there's no need to go digging for URLs in the HTML. I dunno.

Currently I'm using a shell script where I manually copy and paste the video URLs in and then let the script copy the video IDs for use with Twitch-Chat-Downloader. I would like to skip the manual part.

**Comment by TheSneakySniper** [comment]
Hey @PetterKraabol I already wrote a script for this a couple months ago in bash.
its not in python but it may give you an idea of what twitch calls you need to make
https://hastebin.com/nuwixebuli.bash

**Comment by Gorrrg** [comment]
Yay! _jq_ is exactly what I was looking for.

**Comment by TheSneakySniper** [comment]
@Gorrrg I'm glad I could be of service.

**Comment by PetterKraabol** [comment]
The [refactoring/oop](https://github.com/PetterKraabol/Twitch-Chat-Downloader/tree/refactoring/oop) branch can take arguments `--channel` and `--video` with comma-separated values.

```bash
# Download the last 10 VOD chats from each of these channels
python app.py --channel sodapoppin,reckful,nymn --first 10
```

```bash
# Download chat from multiple videos
python app.py --video 399013263,398510957
```

```bash
# Both arguments can be combined
python app.py --video 398510957 --channel forsen,lirik --first 5
```

This branch uses Twitch's new API, which doesn't provide as many fields as V5. For instance, it doesn't provide the channel's name, so you can't use `{channel[name]}.ssa` as output format.
