### ISSUE TITLE
How do I custom format?

### ISSUE THREAD

**Issue by randyyu13** [PetterKraabol/Twitch-Chat-Downloader#137]
Nothing I change in settings.reference.json actually appears to do anything. I followed the documentation to do so.

**Comment by garoto** [comment]
```
Adding custom formats is easily done in settings.json, located in ~/.config/tcd/ by default
```
From: https://github.com/PetterKraabol/Twitch-Chat-Downloader/wiki/Custom-formats

On Windows, the config file is located at `%USERPROFILE%\.config\tcd\tcdsettings.json`. You need to run the program once for the config file to be populated.
