### ISSUE TITLE
[request] Download all formats in one go.

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#14]
Currently only one file is written to disk with each program start. But I usually want the chat in all formats, so I created a shell script to start TCD four times in a row. But this is inefficient (and not nice towards Twitch) because really the chat only needs to be downloaded once, since the different output is based on the same input JSON.

It would be more convenient when there was an option to either just save all formats or have TCD download the formats you have selected on the command line with (multiple) "-f" in one sweep.

**Comment by PetterKraabol** [comment]
`--format all` will first download JSON data form Twitch and use that for all formats.
`--input ./v123456789.json` can be used to input a JSON file to avoid the Twitch API.

See https://github.com/PetterKraabol/Twitch-Chat-Downloader/wiki/Formats#download-all-formats

**Comment by Gorrrg** [comment]
> `--input ./v123456789.json` can be used to input a JSON file to avoid the Twitch API.
Wow, that's really neat. That way you can easily rewrite every format later when you have made changes to your settings.json!
