### ISSUE TITLE
Option to get relative time from VOD start, maybe subtitle format support

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#2]
Hi Petter,

Twitch Chat Download is an awesome tool that I use in combination with youtube-dl (which doesn't seem to have such a feature) to archive VoDs from streamers. Thank You So Much. And as of now it still works flawlessly with the Twitch API.

I have some feature requests:

1. Add the option to change timezone from UTC to a predefined timezone. I mean you can simply replace UTC with the streamers local time with a text editor, but that gets tedious.

2. Relative timecode without date where 00:00.0 is the start of the video, basically a video referenced timecode. So that way it's easier to find the corresponding part of the video to a specific message.

3. Also what would be cool instead of just doing that, to totally convert the output format to a subtitle file format, like SRT or even better SSA as it supports more color options. I know subtitles makes little sense as some chats are very active, but there are players that can display the subtitles as a list in a seperate window. Also messages that appeared in the same second should be ordered by arbitrary fractions of a second I guess which the Twitch API does not provide. But I don't think it's a big deal if your script just makes up those fractions just for the sake of saving the messages in the correct order. I know this is quite some request.

4. Support command line options and make non-interaction an option so your script can be adopted more easily in shell scripts for different purposes.

I would be most happy about request 2. and 4.

Bye

**Comment by PetterKraabol** [comment]
Hi! Relative time, srt, ssa/ass, start/stop times, api request delay along with a huge performance gain was just added in f9e36483111ff910871a29155c82853907473a47.

I've been playing around with srt (not tested ssa/ass, but it can generate files in those formats). I'll add more options for subtitle duration and ssa/ass.

Take a look at [current docs.md](https://github.com/PetterKraabol/Twitch-Chat-Downloader/blob/f9e36483111ff910871a29155c82853907473a47/docs.md) for available arguments. A video ID is the only necessary argument for no interaction. I'll add a no-interaction argument to prevent being asked to save a new client-id.

**Comment by Gorrrg** [comment]
Wow, this is great progress. And I've already found a [bug](https://github.com/PetterKraabol/Twitch-Chat-Downloader/issues/3), too. Yay! ;)

Btw, would you consider adding your code as a module to youtube-dl? Personally I have no trouble using both programs in combination, but youtube-dl's [chat replay code is broken](https://github.com/rg3/youtube-dl/issues/12266) and other people might really appreciate it.

**Comment by PetterKraabol** [comment]
I will most likely not make this into a module for youtube-dl, but they are free to look at this repo to get an idea of how to fix their code.
