### ISSUE TITLE
Issue - but I fixed it

### ISSUE THREAD

**Issue by MathematicianVogt** [PetterKraabol/Twitch-Chat-Downloader#21]
Howdy, I'm running Python 3.6.2

On line 164 of your code app.py you have

file = open(directory + '/' + videoId + '.txt', 'w', encoding='utf-8')

This caused errors for me, I just took out the encoding to this

file = open(directory + '/' + videoId + '.txt', 'w')

and everything works great.

Nice library.

**Comment by PetterKraabol** [comment]
Hi, encoding was added in #18 to fix #17. Looking into this now.
