### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this functio

### ISSUE THREAD

**Issue by ddurdle** [PetterKraabol/Twitch-Chat-Downloader#22]
Using Python 2.7

Traceback (most recent call last):
  File "app.py", line 164, in <module>
    file = open(directory + '/' + videoId + '.txt', 'w', encoding='utf-8')
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by s1leviathan** [comment]
You should go on the folder tha you have saved the script, right click on the app and use IDLE or anyother program you use , find the line 164 and remove this part , encoding='utf-8'
It should work like new :))

**Comment by ddurdle** [comment]
I found another work around to edit the settings and change format to raw (I figured that out by looking at the source code and it using the open call without encoding if specified as raw).
