### ISSUE TITLE
Program has completely broke.

### ISSUE THREAD

**Issue by TheSneakySniper** [PetterKraabol/Twitch-Chat-Downloader#23]
Due to changes in twitch's API, the program has stopped working completely.

error log:
https://hastebin.com/enurupoqon.sql
os: osx sierra

**Comment by TheSneakySniper** [comment]
Now I have done some reconnaissance on the issue and have discovered that twitch now requires client ID to retrieve chat messages. They also have changed the domain from rechat.twitch.tv to api.twitch.tv.



If you curl the following URL with a twitch client ID, it gives you all of the comments in the standard JSON format. I think that if you require a python json parser, you will be able to quickly and easily extract the comments from the chat. This will require a completely new edition of the application.

https://api.twitch.tv/v5/videos/179720371/comments?cursor=eyJpZCI6IjYzMWZmMTUzLTZlZGEtNDlhZi05N2JkLTdmOTYwNDA5NTIxOCIsImhrIjoiYnJvYWRjYXN0OjI2NDA0NDEwMzY4Iiwic2siOiJBQUFXLXV2djJ3QVU2bWt4T2Z4RUFBIn0f

The video this was extracted from was: https://www.twitch.tv/videos/179720371

**Comment by jdpurcell** [comment]
Yeah Twitch changed the rechat API apparently. The new API is actually simpler and better designed. Just like the rest of their API, it requires the "Accept" and "Client-ID" headers in the request. The first request is simply to:

https://api.twitch.tv/v5/videos/{videoId}/comments?content_offset_seconds=0

To get the first bunch of messages. The "_next" attribute of the response contains the cursor value that you pass to get the next bunch of messages:

https://api.twitch.tv/v5/videos/{videoId}/comments?cursor={nextCursor}

And so on, until finally the response is missing its "_next" attribute, indicating that the end has been reached.

Note that the structure of the message Json is also completely different, so any post-processing code needs to be redone as well.

I author a similar program and was able to get it working again, so you can take a peek at my repo if you need any hints.

**Comment by TheSneakySniper** [comment]
Thanks so much!

**Comment by tezJR** [comment]
Thank you both for the quick detective work! I've used Petter's program too and wondered if it was me. I have no idea how busy you are, but if you have the opportunity, I'd love to see this made compatible with the new API.

**Comment by TheDrHax** [comment]
I have started a total rewrite of this script. It does already support new Twitch API (thanks to @jdpurcell) and saving to .ass format.

Some of functions are not working yet:
* Saving to other formats
* settings.json
* Command line arguments

Message reader implements Iterable interface, so you can just read messages one by one and write them to many files at the same time.

Link: https://github.com/TheDrHax/Twitch-Chat-Downloader/blob/master/app.py

**Comment by s1leviathan** [comment]
Im sorry but since i have like no clue of what i just read  :))) , my question might be 'stupid'... So that means that the app will be functual again in the future? Or is it already ready?

**Comment by Gorrrg** [comment]
The one here isn't functional, but people have already figured out the new API and are working on fixing the app in their own branch. You can either use their branch (which lacks some old features) or wait for Petter to adopt the changes.

**Comment by s1leviathan** [comment]
Thats great , so i asume that the new 'version' is on the link from TheDrHax 's reply?

**Comment by Gorrrg** [comment]
yes, it's the one closest to what TCD was
