### ISSUE TITLE
[feature request] getting video.json for a vod

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#28]
It would be useful to have an option to fetch the raw video JSON (like the one in the examples folder) of a video.

If that's not gonna happen, can anybody tell me how I get fetch it via an URL? And if I need a client ID for it or a web cookie.

**Comment by PetterKraabol** [comment]
Hi, `json` format does this, see [wiki/formats](https://github.com/PetterKraabol/Twitch-Chat-Downloader/wiki/Formats#json). Video and comments are saved in the same file.

Video data is fetched from https://api.twitch.tv/v5/videos/212704998?client_id= *(requires client id)*

**Comment by Gorrrg** [comment]
Oh, I didn't see it because "comment" comes before "video" in the JSON file, that's sufficient I guess. Thank you for the url anyway, it's handy to have.
