### ISSUE TITLE
formats.md: {created_at} and formatting for file path

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#29]
So in order to change how `{created_at}` formatted I have to change the `"timestamp": "%x"`?

The way it is described in _formats.md_ is a bit confusing.

**Comment by PetterKraabol** [comment]
Yes, `"timestamp" : "..."` formats `{created_at}`. I've written a more detailed description of custom formats in [wiki/custom-formats](https://github.com/PetterKraabol/Twitch-Chat-Downloader/wiki/Custom-formats).

Currently, this only formats `created_at` and not not `updated_at` or other timestamps.

**Comment by Gorrrg** [comment]
Ah, cool. I've noticed it will use date and time of my timezone. But what if I want to use the timezone of the streamer?

**Comment by PetterKraabol** [comment]
The Twitch API responds with whatever timezone you're in, so the code would have to convert this, given an argument for a timezone.

I'll take a look at it when I implement more timestamp types, like relative timestamps.

**Comment by Gorrrg** [comment]
Ah, that'd be nice if you'd add an option for overriding the timezone. I really appreciate it that you have taken up work on this project again!!!

**Comment by PetterKraabol** [comment]
`--timezone` for setting a timezone. [List of timezones](https://stackoverflow.com/a/13867319).

Use `{timestamp[absolute]}` or `{timestamp[relative]}`, rather than `{created_at}`.

Run `pip install -r requirements.txt` and update `settings.json`.
