### ISSUE TITLE
I have a question about the %f datetime formatting variable

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#35]
It has a precision of six digits but Twitch only provides three digits. Is there a way to truncate the three zeros?

**Comment by PetterKraabol** [comment]
Since it follows Python's datetime formatting, some Python code is necessary to subtract the last thee characters.

A solution would be to provide an optional  `"millisecond_precision": 3` in the settings file for your format. I'll look into this tomorrow.

**Comment by PetterKraabol** [comment]
Add the following within `"comments": {...}` or `"output": {...}` for your format.
```json
"millisecond_precision": 3
```
