### ISSUE TITLE
"Downloading JSON data..."

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#36]
I have removed `print('Downloading JSON data...')` in json.py because the other formats don't have such a status message. That is just my personal preference. But I wonder will the logging output become more verbose like that for all formats?

**Comment by PetterKraabol** [comment]
Hi, I made some changes. By default, it'll display the progress in percent (finally).

- `--preview` prints all lines.
- `--quiet` suppresses all output.
- `--verbose` will be implemented later for printing what the program is doing. It doesn't make much sense to use this now, but in the future for #13 and #14.
