### ISSUE TITLE
SSA output is missing "Style: " for default style

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#37]
It only shows `Default,Arial,20,65535,65535,65535,-2147483640,-1,0,1,3,0,2,30,30,30,0,0` without the `Style: ` at the beginning.

**Comment by Gorrrg** [comment]
I also noticed it has a lot more values in the Format section than in the Style section. I'm not familiar with how SSA interprets this, but it might cause the subtitle to look not as intended.

**Comment by PetterKraabol** [comment]
I've honestly no idea how these are formatted and configured. I'm following this documentation https://www.matroska.org/technical/specs/subtitles/ssa.html
