### ISSUE TITLE
[bug] Syntax error in app.py

### ISSUE THREAD

**Issue by 1ExplosiveTaco** [PetterKraabol/Twitch-Chat-Downloader#38]
Running app.py in the terminal gives me this:
  File "app.py", line 10
    whitelist: List[str] = None
             ^
SyntaxError: invalid syntax
I might have done something wrong? using python 3 and following the read me directions. Thanks

**Comment by PetterKraabol** [comment]
Hi, I get the same error if I run this in Python 2.7. You might have to use `python3 app.py` if you have multiple versions installed.

Run `python --version` to see your version.

It's valid Python 3 syntax: https://repl.it/repls/ShadyDarkcyanComet
