### ISSUE TITLE
[feature request] Add raw format

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#4]
Raw JSON would be good for debugging, better bug reporting & further parsing with other programs, IMHO.

**Comment by PetterKraabol** [comment]
Raw format has been added in 94418708d6d386c732b1ddbbbb45f4945589f06f.

A JSON array of message objects is written to the output file after downloading all messages. I believe this is the best option as opposed to overwriting the file with an updated JSON object for every message, however, the file will remain empty if the script is interrupted/terminated while downloading.
