### ISSUE TITLE
User color support in SSA

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#40]
Will it have a come back?

**Comment by Gorrrg** [comment]
Ah, I see you're working on it! Cool. Got an idea: make it an option to just do the user name in the user color (and the actual comment in the default color) or the entire comment in the user color or everything in the default color.

**Comment by PetterKraabol** [comment]
Take a look at the `ssa` format in the settings file.

Add something like `{\c&#ff00ff&}` in your comment format. (The script will automatically convert `#` into a `H` for SSA.

For usernames, the `ssa` format already shows you how it's done.
`"default_user_color`" can be set to a color, like `#ff00ff` or `random`, and will be used for users who haven't set a color.
