### ISSUE TITLE
Adding custom SSA syntax in the settings.json

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#41]
I want to change the style of the font in the comment part with SSA markup codes like `{\i1\b1}bolditalic{\i0\b0}`. But obviously it gets interpreted by your parser:

```    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 83 column 94 (char 3040)
```

My the "dialog" line looks like this: ```
"dialogue": "Dialogue: Marked=0,{start},{end},Default,{name},0000,0000,0000,,\{\i1\b1\}{name}: \{\i0\b0\}{text}"```

Maybe change from using curved brackets to something else? Or make escaping the SSA markup work (like I tried in my example)?

**Comment by PetterKraabol** [comment]
It took forever, but it's finally here. There was an issue having SSA and Python use curly brackets, which can't be changed, but they should work together just fine now.

Look in `settings.json` to see how it's done with proper escaping. Put username and message within comments format, instead of dialogue.

**Comment by Gorrrg** [comment]
I tested it with two variants and they both worked fine:
`"format": "{\\i1\\b1\\c&{message[user_color]}&}{commenter[display_name]} {\\i0\\b0\\c&HFFFFFF&}{message[body]}`
`"format": "{\\i1}{\\b1}{\\c&{message[user_color]}&}{commenter[display_name]} {\\i0}{\\b0}{\\c&HFFFFFF&}{message[body]}`

And then a more sophisticated/unconsistent formatting mixing:
`"format": "{\\i1\\b1\\c&{message[user_color]}&\\u1}{commenter[display_name]}{\\u0}: {\\i0}{\\b0}{\\c&HFFFFFF&}{message[body]}"`
...which also works.

Thank you for your work! This is great!
