### ISSUE TITLE
ModelueNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by clammier** [PetterKraabol/Twitch-Chat-Downloader#42]
After I add both video and client IDs, save client (same issue even if I don't save) and hit enter, prompt closes pretty much right away with the following log and error:

![err](https://user-images.githubusercontent.com/6205557/34798572-ea5a6b0e-f65c-11e7-941f-380cbc351011.png)

Any idea what am I doing wrong? :) Thanks!

**Comment by PetterKraabol** [comment]
Hi, looks like you haven't installed required python libraries.

Run this command within the `Twitch-Chat-Downloader` directory.
```bash
pip install -r requirements.txt
```
