### ISSUE TITLE
SyntaxError at app.py, Line 10 (colon after whitelist)

### ISSUE THREAD

**Issue by nomizzz** [PetterKraabol/Twitch-Chat-Downloader#43]
After following the installation instructions in the README and running `python3 app.py` on Ubuntu 14.04 I get a `SyntaxError` at the colon after whitelist.  I'm running Python 3.4.3.

I'm not familiar with Python 3's colon syntax, so this is could be an obvious/easy fix and user error.  

Here's the full output:

```
~/Twitch-Chat-Downloader# python3 app.py -h
  File "app.py", line 10
    whitelist: List[str] = None
             ^
SyntaxError: invalid syntax
```

**Comment by PetterKraabol** [comment]
Hi, this is Python's way of defining [type hints](https://docs.python.org/3/library/typing.html) for variables and return values.

You'd have to update your Python to run the script, as this was added in 3.5.

**Comment by anden11** [comment]
I'm having this issue also. Already on Python 3.5.2 so that didn't help

**Comment by cyphase** [comment]
That syntax for variable annotations [was introduced in Python 3.6](https://docs.python.org/3/whatsnew/3.6.html#pep-526-syntax-for-variable-annotations).

**Comment by anden11** [comment]
Indeed, updating to Python 3.6 and installing the dependencies through pip3.6 fixed all the issues for me.
