### ISSUE TITLE
Str object does not support item assignment

### ISSUE THREAD

**Issue by ObjectModule** [PetterKraabol/Twitch-Chat-Downloader#45]
Added both client and video ID's, and saved the client, this error popped up 
![screenshot 2](https://user-images.githubusercontent.com/35740313/35291807-29bfe0fe-0034-11e8-8231-fae10ce0e5ff.png)
Im pretty new to this kind of thing, so any help would be appreciated. Thanks in advance.

**Comment by PetterKraabol** [comment]
Hi, I'm unable to reproduce this.

Post your Python version, the command you're running and if you changed anything.

**Comment by ObjectModule** [comment]
Python 3.6.4
opened git bash within the directory where I cloned Twitch Chat Downloader, which was in gits directory and used python app.py 
![screenshot 2](https://user-images.githubusercontent.com/35740313/35355201-35824d80-0112-11e8-9095-fc928d7cf573.png)

changed directory to it in cmd and used app.py which performed the same 
![screenshot 4](https://user-images.githubusercontent.com/35740313/35355214-3ef299b0-0112-11e8-8f4c-4589422c053b.png)

used IDLE to open the file and run the module which provided the same error
![screenshot 5](https://user-images.githubusercontent.com/35740313/35355403-d44f422e-0112-11e8-91f7-691211637c96.png)

used the shell 
![screenshot 3](https://user-images.githubusercontent.com/35740313/35355232-49c56958-0112-11e8-8e74-3c931ea309f7.png)

didnt edit any py files

**Comment by PetterKraabol** [comment]
Your client ID has a forward slash, which shouldn't be there. Copy your client ID from Twitch again into `settings.json`, where it says `"client_id" : "..."` on the second line.

I get the same error when I invalidate my client ID. You may have selected more than just the client id when you copied it
