### ISSUE TITLE
Question about "default_user_color"

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#46]
I've set it to `"default_user_color": "#ffffff"` but it still assigns random colors to a user. Isn't that supposed to be the correct format?

Also wouldn't it be handy to create a random user color out of the hash of a user's name or even better their Twitch ID? Currently random will give each comment a random color even if it's from the same user, and that's actually really confusing when I read it.

**Comment by PetterKraabol** [comment]
Good idea for having consistent colors!

`default_user_color` was simply misplaced and should be in `"comments": {...}`.
