### ISSUE TITLE
Special user badges in SSA

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#49]
For broadcaster, mods, subscribers etc... IRC log has them, SSA doesn't. It would be a good idea to make it an optional field, like in the IRC format `{commenter[irc_badge]}`. But instead of `irc_badge` it's `badge` for both IRC and SSA. ;)

**Comment by PetterKraabol** [comment]
Are you asking for user-defined badges?

I'd like to make `"badges": {"mod": "@", "admin": "!",...}` avabilable for formats to define custom badges like `[mod]` instead of `@` and just use `{commenter[badge]}` for these.

**Comment by Gorrrg** [comment]
Ah, that's a cool idea. I hadn't thought that far actually. But that's probably the best to do.
