### ISSUE TITLE
User colors should be BGR not RGB

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#50]
~~I've noticed that in the SSA subtitle my user color wasn't the same color that I have set it on twitch.tv. I thought that `default_user_color` only sets the user color for users that haven't set their colors in their Twitch chat settings.~~

EDIT: Oh no, it's actually something different. The RGB values are reversed. SSA uses BGR not RGB... old bug, I think you did the same mistake with the old API as well... ;)

**Comment by PetterKraabol** [comment]
Yep, I remember this being a thing. I'm on it.
