### ISSUE TITLE
How get Twitch Client ID

### ISSUE THREAD

**Issue by Cyberpaul88** [PetterKraabol/Twitch-Chat-Downloader#52]
Since i'm not good at programming, how can i get a Twitch Client ID? Twitch forum isn't so much clear about it.

**Comment by PetterKraabol** [comment]
Hi, head over to https://glass.twitch.tv/console/apps and click the purple Register Your Application button. Choose a name, use http://localhost as OAuth redirect URL and set a category. Once it's created, you'll get a client id.

It will probably ask you to connect your Twitch account first.

**Comment by Cyberpaul88** [comment]
Everytime I add the ID client, the app.py file crashes

**Comment by PetterKraabol** [comment]
You might've included newlines when you copied the ID. Open the settings.json file and paste it in `client_id`.

**Comment by Cyberpaul88** [comment]
client_id was null, so I set Twitch ID as new value but still crashes.
Here, that's what happens. 
![immagine](https://user-images.githubusercontent.com/39853040/41480857-1c230716-70d0-11e8-8068-ed6d474ab756.png)

**Comment by PetterKraabol** [comment]
Looks like you haven't installed the `requests` module with pip.

Run `pip3 install -r requirements.txt`

**Comment by Cyberpaul88** [comment]
Now I get this message.
![immagine1](https://user-images.githubusercontent.com/39853040/41510364-94dc8f80-7263-11e8-8060-33b91feef862.png)

**Comment by PetterKraabol** [comment]
You must run the command from the Twitch-Chat-Downloader directory, where requirements.txt lies.

**Comment by PetterKraabol** [comment]
`python -m pip install -U requests python-dateutil pytz`

If you have Python 2.7 installed too, you might have to use `python3` instead of just `python`.

**Comment by Cyberpaul88** [comment]
If I use the first code,  the console shows this

![immagine4](https://user-images.githubusercontent.com/39853040/41728267-ac6fc50c-7576-11e8-9975-8cc706650223.png)

If i use python3, it shows an error

![immagine5](https://user-images.githubusercontent.com/39853040/41728362-f1c04118-7576-11e8-910a-2e551d846071.png)

**Comment by PetterKraabol** [comment]
I meant  `python3 -m pip install -U requests python-dateutil pytz`

**Comment by Cyberpaul88** [comment]
Still crashing :(

**Comment by PetterKraabol** [comment]
Sure. Read whatever error messages you are getting and they should tell you what's missing.

**Comment by Cyberpaul88** [comment]
Finally! 
I've got where I was mistaking: I used the `app.py` to launch the API, instead I should have used prompt with command `python app.py`.

Thank you!

**Comment by PetterKraabol** [comment]
Awesome! Take a look at custom formats on the wiki https://github.com/PetterKraabol/Twitch-Chat-Downloader/wiki/Custom-formats
