### ISSUE TITLE
Way to not download messages posted from the vod?

### ISSUE THREAD

**Issue by Testing0123** [PetterKraabol/Twitch-Chat-Downloader#55]
Is this possible? There's a way to disable vod messages in the web client

**Comment by PetterKraabol** [comment]
Implemented in the [refactoring/oop](https://github.com/PetterKraabol/Twitch-Chat-Downloader/tree/refactoring/oop) branch at https://github.com/PetterKraabol/Twitch-Chat-Downloader/commit/3459933ac2f49bc0bd7ecf5b0edb7c1a43ee6cf0.

```
"default": {
    "comments": {
        ...
        "ignore_new_comments": true
    },
    "output": {
        ...
    }
},
```
