### ISSUE TITLE
AttributeError: module 'twitch' has no attribute 'chat'

### ISSUE THREAD

**Issue by dude22072** [PetterKraabol/Twitch-Chat-Downloader#59]
> C:\Users\josep\Downloads\Twitch-Chat-Downloader-master\Twitch-Chat-Downloader-master>py -3 app.py -v 348839719 -f ssa
> Traceback (most recent call last):
>   File "app.py", line 4, in <module>
>     import app
>   File "C:\Users\josep\Downloads\Twitch-Chat-Downloader-master\Twitch-Chat-Downloader-master\app\__init__.py", line 3, in <module>
>     from .downloader import download, draw_progress
>   File "C:\Users\josep\Downloads\Twitch-Chat-Downloader-master\Twitch-Chat-Downloader-master\app\downloader.py", line 6, in <module>
>     import app.formats as formats
>   File "C:\Users\josep\Downloads\Twitch-Chat-Downloader-master\Twitch-Chat-Downloader-master\app\formats\__init__.py", line 1, in <module>
>     from .formats import use
>   File "C:\Users\josep\Downloads\Twitch-Chat-Downloader-master\Twitch-Chat-Downloader-master\app\formats\formats.py", line 4, in <module>
>     import app.twitch as twitch
>   File "C:\Users\josep\Downloads\Twitch-Chat-Downloader-master\Twitch-Chat-Downloader-master\app\twitch\__init__.py", line 1, in <module>
>     from .video import Video
>   File "C:\Users\josep\Downloads\Twitch-Chat-Downloader-master\Twitch-Chat-Downloader-master\app\twitch\video.py", line 5, in <module>
>     import twitch
>   File "C:\Users\josep\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twitch\__init__.py", line 1, in <module>
>     from .chat import Chat
>   File "C:\Users\josep\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twitch\chat\__init__.py", line 1, in <module>
>     from .chat import Chat
>   File "C:\Users\josep\AppData\Local\Programs\Python\Python36-32\lib\site-packages\twitch\chat\chat.py", line 4, in <module>
>     import twitch.chat as chat
> AttributeError: module 'twitch' has no attribute 'chat'

**Comment by PetterKraabol** [comment]
Hi, make sure you are using Python >=3.7 and check if you have any conflicting packages that are imported with `import twitch`.

If you use several Python packages for Twitch, you might want to use [pipenv](https://github.com/pypa/pipenv) to avoid import conflicts.
