### ISSUE TITLE
[bug] Unicode conversion fails

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#6]
This is the error message:
`Traceback (most recent call last):
	File "D:\Downloads\Software\(new)\Twitch-Chat-Downloader-master 2017-03-14\app.py", line 254, in <module>
		line = 'Dialogue: Marked=0, ' + subtitleStart[:-4] + ', ' + subtitleStop[:-4] + ', Default, ' + sender + ', 0000, 0000, 0000 , , {\c&H' + color + '&}' + sender + '{\c&H000000&}: ' + text + '\n'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 34: ordinal not in range(128)`

And this is the raw JSON that causes the error:
`{"attributes": {"from": "rainylace", "room": "threemilkt", "tags": {"turbo": false, "sent-ts": "1488508496364", "tmi-sent-ts": "1488508496502", "color": "#5F9EA0", "room-id": "147210100", "emotes": null, "subscriber": false, "user-type": null, "display-name": "rainylace", "user-id": "147820243", "id": "7dac8816-21ee-4b4a-901b-313676b974a8", "badges": null, "mod": false}, "deleted": false, "timestamp": 1488508482049, "color": "#5F9EA0", "command": "", "message": "my username is based on aesthetics\u2122"}, "type": "rechat-message", "id": "chat-9-2017:AVqSBTCczvyLkzIQiULL", "links": {"self": "/rechat-message/chat-9-2017:AVqSBTCczvyLkzIQiULL"}},`

It's probably the trademark sign ™ (U+2122). It was converted to the actual ™ character just fine with your old SSA code. Maybe a unicode/ascii mix-up when concatenating strings?

**Comment by Gorrrg** [comment]
can be fixed by converting the new color variable to string:

```
            if color is None:
                color = 'FFFFFF'
            else:
                color = color.replace('#', '')
                color = rev(color)
                
            color = str(color)
```

That together with the RGB->BGR swap can probably be condensed into a single line... but I'm not actually programmer. :stuck_out_tongue_closed_eyes:

**Comment by PetterKraabol** [comment]
Did `color = str(color)` actually fix this? `color` should already be a string at that point.

If you remember the video ID and timestamp, post them here so I can download the message causing the error.

**Comment by Gorrrg** [comment]
Yes, I'm pretty sure it was the str() that fixed it.

And sorry, but the VOD has been deleted by the site already because it was released more than 14 days ago.
