### ISSUE TITLE
Subtitles for streams lasting over 24 hours store timestamps in wrong format

### ISSUE THREAD

**Issue by dotted** [PetterKraabol/Twitch-Chat-Downloader#62]
Unfortunately the stream in question is no longer available because it has expired, but any stream over 24 hours in length suffers from this.

Command used to download subtitles:

`python app.py -v 365966431 -f all --timezone GMT`

An example line yielded from that command gives:

`Dialogue: Marked=0,1 day, 14:30:48.37,1 day, 14:30:50.37,Default,tielqt,0000,0000,0000,,{\c&H20A5DA&}tielqt {\c&HFFFFFF&}squadala`

But neither VLC or MPC-HC players understand the "1 day" in the timestamp format, but works fine if replaced with absolute hours ie.:

`Dialogue: Marked=0,38:30:48.37,38:30:50.37,Default,tielqt,0000,0000,0000,,{\c&H20A5DA&}tielqt {\c&HFFFFFF&}squadala
`
So instead of `1 day, 14` it should simply say `38`

**Comment by PetterKraabol** [comment]
Thanks!

TCD will now add days to hours. I also noticed that SSA uses centiseconds instead of milliseconds.

[Implementation on repl.it](https://repl.it/@PetterKraabol/ssa-timestamp-formatter)
