### ISSUE TITLE
Could not find tcd-3.0.3-py3.7.egg\tcd\settings.reference.json

### ISSUE THREAD

**Issue by ruby840124** [PetterKraabol/Twitch-Chat-Downloader#65]
hello~
I have installed tcd and I have determined that the version is the same as the requirement. 
But when I type the "tcd" command, 
I get this error:
**[Critical]: Could not find C:\Anaconda3\envs\ruby-twitch\lib\site-packages\tcd-3.0.3-py3.7.egg\tcd\settings.reference.json**

Thank you very much for your answer.

**Comment by PetterKraabol** [comment]
Hi, I've made some changes for including the settings reference. Try updating to 3.0.5.
