### ISSUE TITLE
ModuleNotFoundError: No module named 'rx.subjects'

### ISSUE THREAD

**Issue by systwi** [PetterKraabol/Twitch-Chat-Downloader#69]
Hey there, been using TCD for a while now, great little program! Perfect tool for archivists like myself.

Although, today I ran into a bit of an issue. I updated all of my Python stuff, and afterwards I noticed TCD wasn't working anymore. Here's what I get:

```
systwis-MacBook-Air:~ systwi$ tcd
Traceback (most recent call last):
  File "/usr/local/bin/tcd", line 6, in <module>
    from tcd import main
  File "/usr/local/lib/python3.7/site-packages/tcd/__init__.py", line 7, in <module>
    from .downloader import Downloader
  File "/usr/local/lib/python3.7/site-packages/tcd/downloader.py", line 9, in <module>
    from twitch import Helix
  File "/usr/local/lib/python3.7/site-packages/twitch/__init__.py", line 1, in <module>
    from .chat import Chat
  File "/usr/local/lib/python3.7/site-packages/twitch/chat/__init__.py", line 1, in <module>
    from .chat import Chat
  File "/usr/local/lib/python3.7/site-packages/twitch/chat/chat.py", line 3, in <module>
    from rx.subjects import Subject
ModuleNotFoundError: No module named 'rx.subjects'
```

Adding extra flags still produces the same errors. I'm using macOS 10.13.6 and Python 3.7.4.

**Comment by james-scheckowitz** [comment]
Hello,

Piggybacking on systwi's issue, I've been encountering the same error today for which no module named 'rx.subjects' is being found (trying to use TCD for the first time actually). I'm using macOS 10.14.5 and Python 3.7.3.

**Comment by PetterKraabol** [comment]
Hi, looks like RxPY made some breaking changes. I'm on it

**Comment by PetterKraabol** [comment]
Fixed in https://github.com/PetterKraabol/Twitch-Python/commit/89c67fa1a47f83d96a9b831467e488952d688b43

`pip install --user --update tcd` to 3.1.1

**Comment by molster** [comment]
did a fresh update of TCD today, and im now getting this same error

**Comment by PetterKraabol** [comment]
Which version of rx do you have? tcd 3.2.0 with rx 3.1.0 should work fine
