### ISSUE TITLE
Timezone, "created_at" formatting, russian language in title

### ISSUE THREAD

**Issue by EnterGin** [PetterKraabol/Twitch-Chat-Downloader#70]
Hello!

I have a few questions about your beautiful program.

Firstly, is it possible to somehow change the output format of "created_at"? It has this output format: YYYY-MM-DDTHHmmssZ. It would be nice if the format were: YYYYMMDD.

Secondly, does timezone somehow affect on "created_at"? When changing timezone, the date does not change.

Thirdly, Russian letters in the stream title are not saved in the output file. How can this be fixed?
![cmd_Tyks17t3tm](https://user-images.githubusercontent.com/51099894/61496013-8cf39000-a9c3-11e9-930e-45587595c76d.png)

**Comment by PetterKraabol** [comment]
Hi,

Use `{timestamp[absolute]}` instead of `{created_at}` if you want to specify timezone and formatting.

```json
"output" {
    "format": "{user_name}-{id} - {timestamp[absolute]}.txt",
    "timestamp": {
        "absolute": "%Y%m%d"
    }
}
```

https://github.com/PetterKraabol/Twitch-Chat-Downloader/commit/54b1d7b1b227f5e241f0e06ba77666c311ddb318 changes the character stripping for filenames, so Russian will work now.

`pip install --upgrade --user tcd`

**Comment by EnterGin** [comment]
Thank you!

**Comment by JAK0723** [comment]
This change messes up my preferred output format of `{user_name}/{id} - {title} ({created_at}).log`. The parentheses around the date are now stripped from the filename.

Could it be possible to allow users to define a valid file name themselves? It could be a new field in the settings file, like `"valid_filename_regex": "[^ -()\w.]"`.

**Comment by PetterKraabol** [comment]
@JAK0723 I've added this to 3.1.3. Upgrade and run `tcd` once to update your settings file.
By default, valid letters are `[^-\w.()\[\]{}@%! ]`. Remember to escape backslashes when specifying regex in json.

**Comment by JAK0723** [comment]
I've only tried the default regex so far, but it seems to be working exactly how I want. Thank you!
