### ISSUE TITLE
Is there a way to append comments for SSA?

### ISSUE THREAD

**Issue by chrstnsmthng** [PetterKraabol/Twitch-Chat-Downloader#72]
I want to emulate Twitch chat in the SSA subtitles and I noticed if you append the previous comment (recursively) you could emulate the chat in the subtitles. How could I edit the SSA format for that result?

**Comment by PetterKraabol** [comment]
You can try changing the `End` time for SSA to a very high number in the settings

```ssa
# default
"dialogue": "Dialogue: Marked=0,{start},{end},Default,{commenter[display_name]},0000,0000,0000,,{comment}",`

# new 
"dialogue": "Dialogue: Marked=0,{start},99:00:00.00,Default,{commenter[display_name]},0000,0000,0000,,{comment}",
```

Open the ssa file in Aegisub if you want to play around with styling.
