### ISSUE TITLE
Not able to download JSON file format.

### ISSUE THREAD

**Issue by R1234A** [PetterKraabol/Twitch-Chat-Downloader#75]
Hi, 

I am trying to get the JSON file as output and using this command to get the JSON file as an output. But I think something is missing on my end. Can anybody let me know the exact command to create a JSON file as an output?

`tcd -f json -v 495212030 -t /path/to/folder/`
                       or
`tcd -f all -v 495212030 -t /path/to/folder/`

**Comment by PetterKraabol** [comment]
Hi, use `-o` or `--output` to specify output directory, not `-t`
