### ISSUE TITLE
Default file write location is not Windows standard

### ISSUE THREAD

**Issue by ibex-are-goats** [PetterKraabol/Twitch-Chat-Downloader#78]
Currently files are written to the user's root directory. This is a practical problem because no windows user knows to look there. To find the files output by TCD I had to use verbose mode to find the file name of the output and then I had to search the system for that file to find it in the root directory.

Basically nothing should be there in windows. I checked my old windows install and it's just a couple logs from an AMD chipset driver installer. 

Now of course, knowing exactly where to put them in windows is difficult. There have been many historic standards, and even more non-standard but popular ways of doing it. I'm going to fast-forward through the stories and just say it should be in the "Twitch Chat Downloader" folder in the user's Documents folder. 

To do this, I believe we either 1) assume they're using Windows 10 and use the Twitch Chat Downloader folder in the documents folder:

os.path.join(os.path.expanduser('~'), 'Documents', 'Twitch Chat Downloader')

Or 2) use this to pull the actual documents path from the registry: https://gist.github.com/mkropat/7550097

Unfortunately windows is a little stupid and doesn't have an environment variable for the documents folder.

**Comment by PetterKraabol** [comment]
It's supposed to output files to your current working directory by default. If you run `tcd` from your home directory, chat files should be placed there.
https://github.com/PetterKraabol/Twitch-Chat-Downloader/blob/360d86f091b5026a25322ee00606c3fd6d9fcb2a/tcd/__init__.py#L26
