### ISSUE TITLE
Twitch OAuth Changes

### ISSUE THREAD

**Issue by JAK0723** [PetterKraabol/Twitch-Chat-Downloader#85]
I just received an email from Twitch concerning my use of Twitch-Chat-Downloader and Twitch's endpoints. It states:

> We’ve identified that your Twitch application below is accessing one or more Helix Twitch API endpoints without a valid Twitch OAuth token. We would like to remind you that valid OAuth tokens will soon be required for all Helix endpoints starting on April 30, 2020.

Is there anything I can do to address this issue?

**Comment by EnterGin** [comment]
It happened 
![image](https://user-images.githubusercontent.com/51099894/80999138-d9259900-8e4c-11ea-99cf-d142fba89fe0.png)

**Comment by garoto** [comment]
Apparently, this is happening on and off since May 1st.

**Comment by eugenechung81** [comment]
Submitted pull request to address this issue https://github.com/PetterKraabol/Twitch-Chat-Downloader/pull/86.  Added in oauth-token as a command line parameter.

**Comment by PetterKraabol** [comment]
Twitch-chat-downloader 3.2.0 will now ask for a client-secret to fetch the oauth token from twitch. Seems to be working fine with the API.
