### ISSUE TITLE
"OAuth token is missing" 

### ISSUE THREAD

**Issue by AndrewMarines** [PetterKraabol/Twitch-Chat-Downloader#87]
After two months of using this, today i keep having the error 401 "OAuth token is missing" . Tips?

**Comment by PetterKraabol** [comment]
Related to #85 
Update to 3.2.0

**Comment by AndrewMarines** [comment]
How can i do that? i tried with pip install tcd but it says i'm at the last version

**Comment by PetterKraabol** [comment]
`pip install --upgrade tcd`
