### ISSUE TITLE
Entering wrong client secret breaks app

### ISSUE THREAD

**Issue by ibex-are-goats** [PetterKraabol/Twitch-Chat-Downloader#88]
And I don't know how to fix it! Uninstalling didn't work. I entered Client ID because I wasn't sure what to enter, so the app's description text can be made more verbose and clear too.

Traceback (most recent call last):
  File "c:\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python38\Scripts\tcd.exe\__main__.py", line 7, in <module>
  File "c:\python\python38\lib\site-packages\tcd\__init__.py", line 65, in main
    Arguments().oauth_token = requests.post(f"https://id.twitch.tv/oauth2/token"
KeyError: 'access_token'

**Comment by garoto** [comment]
`tcd --client-secret <secret>`

**Comment by loutlot** [comment]
First, you should re-install through git.
`pip install git+https://github.com/PetterKraabol/Twitch-Chat-Downloader`
Since pip doesn't have latest tcd version, allows you to add --client-secret.
And then
`tcd --settings`
To see wheres your config file.
Go to the directory and open json, add your client id and client secret to the place they should be at.
Hope this works for you.

**Comment by garoto** [comment]
>  Since pip doesn't have latest tcd version, allows you to add --client-secret.

?
```
> pip show tcd
Name: tcd
Version: 3.2.0
Summary: Twitch Chat Downloader
Home-page: https://github.com/PetterKraabol/Twitch-Chat-Downloader
Author: Petter Kraabøl
Author-email: 
License: MIT
Location: j:\misc\python-3.8.2-amd64\lib\site-packages
Requires: twitch-python, python-dateutil, rx, pytz, requests
Required-by:
```

**Comment by PetterKraabol** [comment]
You can run `tcd` again with `--client-secret` and/or `--client-id` to replace your existing settings.

You can also open the settings file at `$HOME/.config/tcd/settings.json` and change the values there.

**Comment by SenouciMoulay** [comment]
> --client-secret
Hi, how can we change the client id, and secret ID in the settings file ?
