### ISSUE TITLE
Unicode gives error

### ISSUE THREAD

**Issue by Far-Se** [PetterKraabol/Twitch-Chat-Downloader#92]
When I try to pull streams that have in title special characters like 'ăîșț' etc it crashes:

``Traceback (most recent call last):
  File "python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,``

 `` File "python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)``

 `` File "Python38-32\Scripts\tcd.exe\__main__.py", line 9, in <module>``

``  File "python38-32\lib\site-packages\tcd\__init__.py", line 92, in main
    Downloader().channels(Arguments().channels)``

``  File "python38-32\lib\site-packages\tcd\downloader.py", line 194, in channels
    Logger().log(format('\n{}'.format(video.title)), Log.REGULAR)``

``  File "python38-32\lib\site-packages\tcd\logger.py", line 63, in log
    print(log)``

``  File "python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]``

``UnicodeEncodeError: 'charmap' codec can't encode character '\u0103' in position 3: character maps to <undefined>
``

Can it be fixed?

**Comment by PetterKraabol** [comment]
Related to #90

Upgrade tcd to v3.2.1
