### ISSUE TITLE
Is it possible to lunch tcd inside another python script?

### ISSUE THREAD

**Issue by Pelirrojo** [PetterKraabol/Twitch-Chat-Downloader#98]
Hi,

I'm trying to automate the downloads of some chats, and I'm wondering if is it possible to make through another code, using tcd as library instead CLI command. I'm still landing at python.

Thanks in advance,
Manuel

**Comment by sctheise** [comment]
@Pelirrojo this article I found should be able to help you use tcd in scripts

[https://janakiev.com/blog/python-shell-commands/](url)

**Comment by Pelirrojo** [comment]
Thanks you too much!

I'll try with subprocess but tcd needs a hidden file at user's home and that it isn't compatible with the current environment that I'm using :)

Thanks anyway for helping, the article it's interesting and much more extensive that I know!
